services:
  kino.api:
    image: kino.api
    env_file: api.env
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Kino.Api/Dockerfile
    depends_on:
      - kino.db
  kino.db:
    container_name: kino_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - 2433:1433
    volumes:
      - db:/var/opt/mssql
volumes:
  db:
    name: kino_db